parameters:

services:
    monitor.command.get_actual_adverts:
        class: MonitorBundle\Command\GetActualAdvertCommand
        arguments:
            - @monitor.service.advert
        tags:
            - { name: console.command }
