parameters:

services:
    monitor.command.get_actual_adverts:
        class: MonitorBundle\Command\GetActualAdvertCommand
        arguments:
            - @monitor.service.advert
            - @logger
        tags:
            - { name: console.command }

    monitor.daemon.search:
        class: MonitorBundle\Command\SearchDaemonCommand
        arguments:
            - @monitor.service.search
            - @logger
        tags:
            - { name: console.command }
