imports:
    - { resource: commands.yml }
    - { resource: repositories.yml }
    - { resource: cache.yml }

parameters:

services:
    monitor.service.search:
        class: MonitorBundle\Service\SearchService
        arguments:
            - @monitor.repository.search
            - @monitor.repository.user
