parameters:

services:
    monitor_api.controller.search:
        class: MonitorApiBundle\Controller\SearchController
        arguments:
            - @monitor.service.search
        calls:
            - [ setContainer, [ @service_container ]]
            - [ setNormalizer, [ @serializer ]]

    monitor_api.controller.advert:
            class: MonitorApiBundle\Controller\AdvertController
            arguments:
                - @monitor.service.advert
            calls:
                - [ setContainer, [ @service_container ]]
                - [ setNormalizer, [ @serializer ]]

    monitor_api.controller.user:
        class: MonitorApiBundle\Controller\UserController
        arguments:
            - @monitor.service.user
        calls:
            - [ setContainer, [ @service_container ]]
            - [ setNormalizer, [ @serializer ]]
